ALTER TABLE meal_plans DROP COLUMN IF EXISTS source_plan_id;
ALTER TABLE meal_plans ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ;
ALTER TABLE meal_plans ADD COLUMN IF NOT EXISTS reused BOOLEAN NOT NULL DEFAULT FALSE;
